# PMM.rnc
# Kim Steen Ravn:
# 2012:01:16; sigler
# 2012:01:11: skriftgrad, div title and text
# 2011:10.10: skema lagt p pmm.dsl.dk/../skema-pmm; nyt navn
# 2011.09.11: annotering, nye elementer og att.
# 2011.07.18: ny teiHeader
# 2011.03.24; 2011.03.09 (head > title); 2011.03.08; 2011.02.28
# 2012:06:26: attribute på witness etc
# 2012.07.04: note inddirkete udviddet med NF
# Holger Berg
#omdoebt til sv18.rnc
#2023-03-17: tilpasset 18-binds-udgaven

datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"
namespace ns1 = "http://www.tei-c.org/ns/1.0"

include "tei_all.rnc" {

teiHeader =
   # <teiHeader> generel beskrivelse af filens indhold, ndringer, hvem som gr hvad, etc.
   element ns1:teiHeader {
      # <fileDesc> beskriver filens indhold
      element ns1:fileDesc {
         # <titleStmt> beskrivelse af grundtekst
         
         element ns1:titleStmt {
            # <title> indeholder tekstens titel
            element ns1:title {
               # vrdien i corresp er kommentarens filnavn
               #attribute corresp { xsd:string { pattern="com[0-9]+.xml" } } ?,
               # main bruges til selvstndig titel, part til titel som del af fx tidsskrift, indlg i avis
               #attribute type { xsd:string { pattern="main|part" } },
               # vrdien i xml:id er filnavnet
               #attribute xml:id { xsd:ID { pattern="txt[0-9]+.xml" } },
            text },
            # <author> er Poul Martin Mller
            element ns1:author {
            attribute ref { xsd:string {pattern="http://viaf.org/viaf/4925902"}}?,
            
            xsd:string{ pattern="Hans Christian Andersen"} },
            # <editor> indeholde navnet p den som har etaberet teksten
            element ns1:editor { 
               attribute role { xsd:string { pattern="text" } } ,
            text } * ,#xsd:string { pattern="Finn Gredal Jensen|Karsten Kynde|Kim Steen Ravn" }
            element ns1:editor { 
               attribute role { xsd:string { pattern="data" } } ,
             text } * ,#xsd:string { pattern="Finn Gredal Jensen|Karsten Kynde|Kim Steen Ravn" }
            element ns1:editor { 
               attribute role { xsd:string { pattern="data" } } ,
            text } * ,#xsd:string { pattern="Finn Gredal Jensen|Karsten Kynde|Kim Steen Ravn" }            
            element ns1:editor { 
               attribute role { xsd:string { pattern="editor" } },
             text } * ,#xsd:string { pattern="Finn Gredal Jensen|Karsten Kynde|Kim Steen Ravn" }           
            element ns1:editor { 
               attribute role { xsd:string { pattern="editor" } },
             text } * ,#xsd:string { pattern="Finn Gredal Jensen|Karsten Kynde|Kim Steen Ravn" }
            element ns1:respStmt {
               element ns1:resp { text },
               element ns1:name { text },
            empty } *,
            element ns1:xenoData { text } *,
         empty },
         # <publicationStmt> indeholder oplysninger om institutionen bag udgivelsen
         element ns1:publicationStmt {
            element ns1:publisher { xsd:string { pattern="Museum Odense and The Hans Christian Andersen Center, University of Southern Denmark, Odense, Denmark" } },
            # <availability> indeholder oplysninger tilgngelighed, copyrights, etc.
            element ns1:availability {
               # <p> indeholder beskrivelsen af availability
               element ns1:p { 
               attribute type { xsd:string{ pattern="cc-by"}},
               attribute target { xsd:string{ pattern="https://creativecommons.org/licenses/by/4.0/"}},
               xsd:string { pattern="Creative Commons, Attribution 4.0 International \(CC BY 4.0\)"} } *,#http://pmm.dsl.dk/(afhandlinger|anmeldelser|breve|digte|drama|en-dansk-students-eventyr|forelaesninger|oversaettelser|polemik|prosa|stroetanker)/(trykte|manuskript)/(txt|com)[0-9]*.xml
               element ns1:p { text } *,
            empty },
            # <idno> oplysninger om versionsnummer
            element ns1:idno {
               # att. angiver at der er tale om version
               attribute type { xsd:string { pattern="version[0-9].[0-9]" } },
            text },
            # <date> publikationsdato, formatet er yyyy-mm-dd
            element ns1:date { xsd:date },
         empty },
         # <sourceDesc> beskrivelse af grundteksten
         element ns1:sourceDesc {
            # <listBibl> indeholder bibliografiske oplysninger om grundteksten
            element ns1:notesStmt {
    model.noteLike+, att.global.attributes, empty
  },
            element ns1:listWit { 
               # <bibl> beskrivelse grundtekst
               attribute xml:id { xsd:ID { pattern="copyText" } },
               element ns1:witness {
                  # xml:id indeholder grundtekstens sigel, A, etc
                  attribute xml:id { xsd:ID { pattern="A|B|ES1|ES2|ES3|K|R|SU|US" } },
               text } *,
            empty }?,
            element ns1:listWit { 
               # <bibl> tekstkilder hvorefter der rettes
               attribute xml:id { xsd:ID { pattern="emandation" } },
               element ns1:witness {
                  # xml:id indeholder tekskildes sigle
                  attribute xml:id { xsd:ID { pattern="ES1|ES2|ES3|K|R|SU|US" } },
               text } *,
            empty } *,
         empty },
         element ns1:encodingDesc{
         taxonomy
         },
         
         xenoData,
      empty },
      profileDesc,
      # revisionslog
      element ns1:revisionDesc { 
         element ns1:change {
            attribute who { xsd:string { pattern="FGJ|KK|KSR|NHB|AS" } },
            attribute when { xsd:date },
            attribute xml:id {xsd:ID}?,
            attribute status {text}?,
            text } *,
      text }     
}

\text =
  element ns1:text {
     attribute type { xsd:string { pattern="ms|print|edition" } },
  ( front & body & divContent )
  }

front =
   element ns1:front {
      element ns1:titlePage {
         element ns1:docTitle {
            element ns1:titlePart {
               attribute type { xsd:string { pattern="main|sub" } },
            text } *,
            empty },
            element ns1:byline {
            text } *,
            element ns1:docImprint {
               element ns1:pubPlace {
               text } &
               element ns1:publisher { 
               macro.phraseSeq } * &
               element ns1:date { 
               text } &
            text },
         text } ?,
         element ns1:div {
            attribute type { xsd:string { pattern="dedication" } },
         divContent } ?,
    empty } ?

body =
   # <body> contains the whole body of a single unitary text
   element ns1:body {
     # <div> bruges til inddeling af teksten; i dele, kapitler, etc.
     element ns1:div {
        attribute type {divTypeContent}?,
        # subtype bruges til at skelne mellem ms. og tryk
        # attribute subtype { xsd:string { pattern="manuscript|print" } } ,
        # type angiver tekstkategorien
        # attribute type { xsd:string { pattern="fragment|novel|poem|prose|song|translation|treatise" } } ,
        # xml:id bruges til nummerering af hver <div>; fragment = strtanker
        # attribute xml:id { xsd:ID { pattern="(chapter|fragment|part|poem)[0-9]+" } } ,
     divContent } *,
   empty }
}

divContent =
   
     
   element ns1:sourceDate 
   {
  divContent } * &


   # <app> tekskritisk apparat
   (element ns1:app {
      # rettelsesnote
      attribute type { xsd:string {pattern="corrNote"} },
      # <lem> lemma
      element ns1:lem {
         # wit rummer siglen for lemmas læsemde
         attribute wit { sigler },
      divContent },
      # <rdg> grundtekstens læsemde
      element ns1:rdg {
         # wit rummer siglen for grundtekstens lsemde
         attribute wit { xsd:string {pattern="A|K|ms.|R"} },
      text }
    } ?
   |
   # supplerende note
   (element ns1:app {
      # rettelsesnote
      attribute type { xsd:string { pattern="suppNote" } },
      # <lem> lemma
      element ns1:lem {
         # wit rummer siglen for lemmas læsemde
         attribute wit { sigler },
      divContent } ,
      # <rdg> reading er valgfri
      element ns1:rdg { 
         attribute wit { sigler },
      divContent } ?,
      # <witDetail> fri udgivertekst
      element ns1:witDetail { 
         attribute rend { witDetailList } ?,
      macro.paraContent } ?,
   empty } ? ) 
   |
   # supplerende note
   (element ns1:app {
       # rettelsesnote
       attribute type { xsd:string { pattern="witDetail" } },
      # <lem> lemma
      element ns1:lem {
         # wit rummer siglen for lemmas læsemde
         attribute wit { xsd:string { pattern="A" } },
      divContent } ,
    # <witDetail> fri udgivertekst
    element ns1:witDetail { 
         attribute rend { witDetailList } ?,
    macro.paraContent } ?,
   empty } ? )
   |
   (element ns1:app {
      # rettelsesnote
      attribute type { xsd:string { pattern="combNote" } },
      # <lem> lemma
      element ns1:lem {
         # wit rummer siglen for lemmas lsemde
         attribute wit { sigler },
      divContent } ,
      (# <rdg> reading er valgfri
      element ns1:rdg { 
         attribute wit { sigler },
      divContent } * &
      # <witDetail> fri udgivertekst
      element ns1:witDetail { 
         attribute rend { witDetailList } ?,
      macro.paraContent }) *,
    empty } ? )) * &
    
    element ns1:bibl {
    (text
     | model.gLike
     | model.highlighted
     | model.pPart.data
     | model.pPart.edit
     | model.segLike
     | model.ptrLike
     | model.biblPart
     | model.global)*,
    att.global.attributes,
    att.declarable.attributes,
    att.typed.attributes,
    empty
  }* &
  
  
    element ns1:cit {
    (model.egLike
     | model.biblLike
     | model.ptrLike
     | model.global
     | model.entryPart
     |quote
     | divContent )+,
    att.global.attributes,
    att.typed.attributes,
    empty
  }* &
  
  
  element ns1:quote{
  (divContent) *
  }* &
  
  \list * &
  
  element ns1:floatingText {
  attribute xml:id { xsd:ID  {pattern = "[\S\-]+"} },
  attribute rend {text},
  (body | divContent)*
  }* &
  
  
  element ns1:cell {
  attribute type { xsd:string }, 
  (body | divContent)*
  }* &
  
  element ns1:row {
  #attribute xml:id { xsd:ID { xsd:string } },
  attribute xml:id { xsd:ID { pattern="txtcmnt-[0-9]{3}-[0-9]{2}" } },
  (body | divContent)*
  }* &
  
  
  element ns1:lemma{
  element ns1:data-term{divContent },
  element ns1:anchor{
  attribute target {text},
    attribute type { xsd:string { pattern="continued" }}?  
    },
  (body | divContent | l)*
  }* &
  
  element ns1:i{text}* &
  
  element ns1:source {text}* &
  
   # <figure> -> graphic skilletegn (csur) 
   element ns1:graphic {
      # type = kort og lang skillestreg, sikkert ogs asterisker etc.
      attribute type { xsd:string { pattern="blank|longLine" } },#asterisk|asterisk3|shortLine|shortLineLeft
   empty } * &
   # <note> element til fod- og marginalnoter
   (element ns1:note {
      # type kan have vrdierne footNote og marginNote
      attribute type { xsd:string { pattern="footnote|marginNote" } },
      element ns1:p { 
      attribute rend { indentValues } ?,
       divContent } *,
   empty }  *
   |
   (element ns1:note {
      attribute corresp { indirect },
      attribute n { xsd:integer },
      attribute rend { xsd:string { pattern="start" } },
      attribute select { xsd:integer } ?,
   empty } *,
   
   signed *,
   
  
  (element ns1:sourceTitle {
  
  attribute type { xsd:string { pattern="main|part"}} *,
  
  
  
  element ns1:source{
  text}?,
  divContent }) *,
  
  
  
  
  element ns1:table {
    ((model.headLike | model.global)*, (row, model.global*)+),
    att.global.attributes,
    
    ## indicates the number of rows in the table.
    attribute rows { xsd:nonNegativeInteger }?,
    
    ## (columns) indicates the number of columns in each row of the table.
    attribute cols { xsd:nonNegativeInteger }?,
    empty
  }*,
  
  element ns1:div {
  attribute type {divTypeContent},
  divContent }*,

  
  ## contains one row of a table. 
  #element ns1:row {
   # cell+, att.global.attributes, att.tableDecoration.attributes, empty
  #}  *,
  
  #element ns1:cell {
   # macro.paraContent,
    #att.global.attributes,
    #att.tableDecoration.attributes,
    #empty
  #} *,   
   element ns1:note {
      attribute corresp { indirect },
      attribute n { xsd:integer },
      attribute rend { xsd:string { pattern="end" } },
      attribute select { xsd:integer } ?,
   empty } * )) &
   element ns1:p { 
      attribute rend { indentContent },
   divContent } * &
   element ns1:head {
      attribute type { headTypeContent },
   divContent } * &
   element ns1:title {
      attribute type { xsd:string { pattern="edition" } },
   divContent } * &
   # <hi> fremhvelser og strrelse i lbende tekst
   element ns1:hi {
      # n angiver strrelse i forhold til brdtekst
      attribute n { xsd:string { pattern="size(-1|1|2|3)" } } ?,
      # rend angiver fremhvelser, fed og kursiv, eller afgvignende skrift, antikva, etc
      attribute rend { hiContent } ?,
   divContent } * & 
   # <lb/> alinea, et element for hver alinea
   element ns1:lb {
   empty } * &
   # <lg> strofer
   element ns1:lg {
      # strofens lokale nummer
      attribute n { xsd:integer { pattern="[0-9]+"} } ?,
      # <l> vers
      (element ns1:l {
         # n-att. nummer
         attribute n { xsd:integer { pattern="[0-9]*[05]" } } ?,
         # rend indrykning af vers
         attribute rend { indentValues } ?,
         #attribute xml:id { xsd:ID { pattern="firstLine" } } ?,
      divContent }
      ) *,
   empty } * &
   text &
   # <pb/> sideskift i grudntekst
   element ns1:pb {
      # ed angiver hviklen type grundtekst der er sideskift i
      attribute ed { xsd:string { pattern="A|ms" } }? ,
      # n sideskift arabertal, store og sm romertal
      attribute n { xsd:string { pattern="[0-9]+|[iIvVxXcC]+" } }? ,
      # type bruges ved stum paginering
      attribute type { xsd:string {pattern="supp"} } ?,
   empty } * &
   # <seg> element til mærknig af lemma
   element ns1:seg {   
      macro.paraContent,
      # type angiver to typer af lemmata; sm og store (overskrider slutmrke)
      attribute type { xsd:Name {pattern="com|comStart|comEnd" }},
      # n = lemmas nummer (NB: et lemma en kommentar, alts svarende til xml:id)
      attribute n { xsd:token {pattern = "com[0-9]+|com[0-9]+-[0-9]+[a-z]|com[0-9]+-[0-9]+"}},
   empty } *

#patterns

# romanType = antikva
hiContent = xsd:string { pattern="bold|initial|italic|spaced|raised|romanType|schwabacher|upperCase" }

# sigler
sigler = xsd:string { pattern="ES(1|2|3)|ES1 ES2 ES3|ES1 ES2|ES1 ES3|ES2 ES3|(K)?|(ms.)?|(R)?|(udg)?|(SU)?|(US)?" }

# formler i fri udgivertekst
witDetailList = xsd:string { pattern="alin|mff|mmt|saaog" }

# left er indrykning fra venstre, right er fra hjre
indentContent = xsd:string { pattern="center|firstIndent|firstIndentRight|hangingIndent|left|noIndent|secondIndent|secondIndentRight|right" }

# indirekte overleveret text
indirect = xsd:string { pattern="ES1|ES2|ES3|NF|US|SU" }


headTypeContent = xsd:string { pattern="main|part|section|section-comments" }

divTypeContent =  xsd:string { pattern="works|work|source|dedication|chapter|comments|part|preface|act|scene|floatingWork" } 

indentValues = xsd:string {pattern="noIndent|center|firstIndent|right|secondIndent"}